classifier:
  encoder_lr: 1.0e-5
  
  mlp:
    balanced: True
    test_prop: 0.1
    target_class: 7
    
    optimizer:
      name: ADAM
      params:
        lr: 0.001
        weight_decay: 0.001
    scheduler:
      name: STEP_LR
      params:
        step_size: 250
        gamma: 0.5

  classifier_trainer:
    max_epochs: 300
    min_epochs: 300
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    check_val_every_n_epoch: 50
    log_every_n_steps: 2
    precision: 32
    detect_anomaly: True
    gpus: 1
    auto_select_gpus: True
    enable_model_summary: False
    num_sanity_val_steps: 10
    track_grad_norm: -1
    enable_checkpointing: False

  model:
    hidden_dims: [64, 32]
    dropout: 0.2
    batch_size: 128
