data:
  dataset: DLPFC
  k_cutoff: 12
  top_genes: 2000
mode: clustering
model:
  cl_temperature: 2.0
  class_num: 7
  cluster_temperature: 0.7
  dic_hidden: 64
  feat_hidden1: 64
  feat_hidden2: 32
  gcn_hidden: 64
  latent_dim: 16
  mask_method: spot
  mask_rate: 0.3
  p_drop: 0.2
  t: 2
seed: 3407
train:
  d_step: 1
  decay: 0.001
  epochs: 1000
  g_step: 1
  gradient_clipping: 5.0
  knn_neigh: 50
  lr: 0.001
  plot_step: 5
  start_step: 500
  t_step: 50
  w_cluster: 0.75
  w_disc: 1.0
  w_recon: 0.2
  w_tri: 0.1
