data:
  dataset: ME
  k_cutoff: 8
  top_genes: 5000
mode: clustering
model:
  cl_temperature: 1.3
  class_num: 15
  cluster_temperature: 3.6
  dic_hidden: 64
  feat_hidden1: 64
  feat_hidden2: 32
  gcn_hidden: 64
  latent_dim: 16
  mask_method: gene
  mask_rate: 0.6
  p_drop: 0.2
  t: 2
seed: 3407
train:
  d_step: 1
  decay: 0.001
  epochs: 1000
  g_step: 1
  gradient_clipping: 5.0
  knn_neigh: 50
  lr: 0.001
  plot_step: 5
  start_step: 500
  t_step: 50
  w_cluster: 0.9
  w_disc: 0.8
  w_recon: 0.1
  w_tri: 0.8
